on:
  push:
    - main
    - build-test
  paths:
    - Dockerfile-amd64
    - Dockerfile-arm64
    - .github/workflows/build.yaml

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push for amd64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-amd64
          platforms: linux/amd64
          push: true
          tags: devops-img:latest

      - name: Build and push for arm64
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile-arm64
          platforms: linux/arm64
          push: true
          tags: devops-img:latest
